local TechTree = require("techtree")

local seg_time = TUNING.SEG_TIME
local day_segs = TUNING.DAY_SEGS_DEFAULT
local dusk_segs = TUNING.DUSK_SEGS_DEFAULT
local night_segs = TUNING.NIGHT_SEGS_DEFAULT
local total_day_time = TUNING.TOTAL_DAY_TIME
local day_time = seg_time * day_segs
local dusk_time = seg_time * dusk_segs
local night_time = seg_time * night_segs

--	Worldgen
	
	TUNING.POLAR_RETROFIT = GetModConfigData("biome_retrofit") or 0
	
	TUNING.POLAR_TASKS_OPTIONALITY = {
		["Polar Floe"] = 0.32,
		--["Polar Lake"] = 0.4,
	}
	
	TUNING.ANTLER_TREE_CHOPS = 10
	TUNING.ANTLER_TREE_CHOPS_REGEN_TIME = total_day_time
	
	TUNING.ICELETTUCE_SPAWNER_CHANCE = 0.25
	TUNING.ICELETTUCE_SPAWNER_MIN = 3
	TUNING.ICELETTUCE_SPAWNER_TIME = {min = day_time, max = total_day_time * 5}
	
	TUNING.GRASS_POLAR_DENSITY = {min = 16, max = 30}
	TUNING.GRASS_POLAR_REEDS_CHANCE = 0.25
	
	TUNING.POLAR_ICICLE_DAMAGE = 300
	TUNING.POLAR_ICICLE_MINE = 3
	TUNING.POLAR_ICICLE_BREAK_CHANCE = 0.33
	TUNING.POLAR_ICICLE_ENABLED = true
	TUNING.POLAR_ICICLE_GROWTIME = seg_time * 2
	TUNING.POLAR_ICICLE_GROWTIME_VARIANCE = total_day_time
	TUNING.POLAR_ICICLE_SPAWNTIME = seg_time
	TUNING.POLAR_ICICLE_ORNAMENT_CHANCE = 0.5
	TUNING.POLAR_MAX_ICICLES = 6
	TUNING.POLAR_WORLD_MAXICICLES = 120
	
	TUNING.POLAR_ROCK_MINE_TALL = 10
	
	TUNING.TUMBLEWIND_SPAWNRATE_EARLY = 1
	TUNING.TUMBLEWIND_SPAWNRATE_LATER = 6
	TUNING.TUMBLEWIND_MAX_DENSITY = 15
	TUNING.TUMBLEWIND_ENABLED = true
	TUNING.TUMBLEWIND_NUMLOOT = 3
	TUNING.WINTER_FOOD_TUMBLEWIND_CHANCE = 0.2
	TUNING.WINTER_ORNAMENT_TUMBLEWIND_CHANCE = 0.1
	
--	Players
	
	TUNING.MIGHTINESS_POLAR_SLOWMULT = 1.5
	TUNING.MIGHTINESS_POLAR_SLOWTIME = 4
	TUNING.WIMPY_POLAR_SLOWMULT = 0.75
	TUNING.WIMPY_POLAR_SLOWTIME = -1
	TUNING.LEGDAY_POLAR_SLOWMULT = 1.25
	TUNING.LEGDAY_POLAR_SLOWTIME = 2
	
	TUNING.WEREMODE_POLAR_SLOWMULT = 1.75
	TUNING.WEREMODE_POLAR_SLOWTIME = 3
	
--	Mobs
	
	TUNING.POLAR_MOOSE_HEALTH = 1000
	TUNING.POLAR_MOOSE_DAMAGE = 50
	TUNING.POLAR_MOOSE_DAMAGE_NOANTLER = 35
	TUNING.POLAR_MOOSE_ATTACK_PERIOD = 3
	TUNING.POLAR_MOOSE_ATTACK_RANGE = 1.5
	TUNING.POLAR_MOOSE_HIT_RANGE = 3
	TUNING.POLAR_MOOSE_ANTLER_HIT_RANGE = 5
	TUNING.POLAR_MOOSE_ANTLER_GROWTIME = total_day_time * 15
	TUNING.POLAR_MOOSE_ANTLER_TARGET_RANGE = 4
	TUNING.POLAR_MOOSE_SHED_MIN_DIST = 25
	TUNING.POLAR_MOOSE_SHED_MIN_VEL = 60
	TUNING.POLAR_MOOSE_SHED_WORK = 5
	TUNING.POLAR_MOOSE_RUN_SPEED = 12
	TUNING.POLAR_MOOSE_WALK_SPEED = 2.5
	
	TUNING.POLAR_PENGUIN_HERD_SPAWN_TIMES = {min = seg_time, max = day_time}
	TUNING.POLAR_PENGUIN_MAX_IN_RANGE = 20
	TUNING.POLAR_PENGUIN_SHORE_DIST = 11
	TUNING.POLAR_PENGUIN_MATING_SEASON_BABYDELAY = 8
	TUNING.POLAR_PENGUIN_MATING_SEASON_BABYDELAY_VARIANCE = 22
	
	TUNING.POLARBEAR_HEALTH = 800
	TUNING.POLARBEAR_HEALTH_REGEN_AMOUNT = 10
	TUNING.POLARBEAR_HEALTH_REGEN_PERIOD = (500 * 2) / (total_day_time * 3) * 10
	TUNING.POLARBEAR_DAMAGE = 50
	TUNING.POLARBEAR_DAMAGE_BITE = 75 -- 97
	TUNING.POLARBEAR_ATTACK_PERIOD = 2
	TUNING.POLARBEAR_BITE_PERIOD = 4
	TUNING.POLARBEAR_BITE_RANGE = 2.5
	TUNING.POLARBEAR_BITE_VEL = 22
	TUNING.POLARBEAR_RAGE_TIME = 12
	TUNING.POLARBEAR_RAGE_RUN_MULT = 1.5
	TUNING.POLARBEAR_RUN_SPEED = 6
	TUNING.POLARBEAR_WALK_SPEED = 3
	TUNING.POLARBEAR_HAT_CHANCE = 0.33
	TUNING.POLARBEAR_PLOWTIME = seg_time * 2
	TUNING.POLARBEAR_BLIZZARD_WARNTIME = total_day_time
	
	TUNING.POLARBEAR_LOYALTY_PER_HUNGER = TUNING.PIG_LOYALTY_PER_HUNGER / 2
	TUNING.POLARBEAR_LOYALTY_MAXTIME = TUNING.PIG_LOYALTY_MAXTIME / 2
	
	TUNING.POLARBEARHOUSE_SPAWN_TIME = total_day_time * 4
	TUNING.POLARBEARHOUSE_ENABLED = true
	
	TUNING.POLARFOX_HEALTH = 200
	TUNING.POLARFOX_DAMAGE = 30
	TUNING.POLARFOX_RUN_SPEED = 8
	TUNING.POLARFOX_WALK_SPEED = 2.5
	TUNING.POLARFOX_LEADER_RUN_DIST = 14 * 14
	TUNING.POLARFOX_LOYALTY_PER_FOOD = total_day_time + seg_time
	TUNING.POLARFOX_LOYALTY_MAXTIME = total_day_time * 3
	TUNING.POLARFOX_HUNT_COOLDOWN = seg_time * 2
	
	TUNING.POLARFOX_SPAWN_TIME = total_day_time
	TUNING.POLARFOX_SPAWN_TIME_VARIATION = total_day_time
	TUNING.POLARFOX_ENABLED = true
	
	TUNING.POLARWARG_HEALTH = 1300
	TUNING.POLARWARG_DAMAGE = 60
	
	TUNING.SHADOW_ICICLER_HEALTH = 200
	TUNING.SHADOW_ICICLER_DAMAGE = 35
	TUNING.SHADOW_ICICLER_ATTACK_PERIOD = 6
	TUNING.SHADOW_ICICLER_ATTACK_RANGE = 20
	TUNING.SHADOW_ICICLER_SPIKE_AMT = {min = 4, max = 9}
	TUNING.SHADOW_ICICLER_SPIKE_HEIGHT = {min = 8, max = 16}
	TUNING.SHADOW_ICICLER_SPIKE_RING_RANGE = {min = 4, max = 8}
	TUNING.SHADOW_ICICLER_SPIKE_RANGE = 2
	TUNING.SHADOW_ICICLER_SPEED = 4
	TUNING.SHADOW_ICICLER_SPAWN_CHANCE = 0.66
	
--  Bosses
	
	TUNING.FROSTY_TARGET_DIST = 14
	TUNING.FROSTY_STAGE1_WALK_SPEED = 3
	TUNING.FROSTY_STAGE1_HEALTH = 5000
	TUNING.FROSTY_STAGE1_DAMAGE = 100
	TUNING.FROSTY_ATTACK_PERIOD = 4
	
--	Items
	
	TUNING.ANTLER_TREE_STICK_ATTACK_PERCENT = 0.0016
	TUNING.ANTLER_TREE_STICK_DAMAGE = 48
	TUNING.ANTLER_TREE_STICK_PERISHTIME = total_day_time * 10
	TUNING.ANTLER_TREE_STICK_SPEED_MULT = 1.25
	
	TUNING.DRYICE_FREEZABLE_COLDNESS = 0.67
	TUNING.ICELETTUCE_COOLING = -5
	TUNING.ICELETTUCE_FREEZABLE_COLDNESS = 2
	TUNING.ICELETTUCE_KILLJOY_TOLERANCE = 0
	
	TUNING.ICICLESTAFF_DAMAGE = 25
	TUNING.ICICLESTAFF_ICICLES_NUM = 15
	TUNING.ICICLESTAFF_SANITY_DELTA = -1
	TUNING.ICICLESTAFF_USES = 25
	
	TUNING.POLARICESTAFF_FREEZE_TIME = 7
	TUNING.POLARICESTAFF_SANITY_DELTA = -1
	TUNING.POLARICESTAFF_USES = 20
	
	TUNING.ARMOR_POLARCROWNHAT = 420
	TUNING.ARMOR_POLARCROWNHAT_ABSORPTION = 0.7
	TUNING.ARMOR_POLARCROWNHAT_BREAK_CHANCE = 0.66
	TUNING.ARMOR_POLARCROWNHAT_BREAK_COOLDOWN = 10
	TUNING.ARMOR_POLARCROWNHAT_FREEZINESS = 0.1
	TUNING.ARMOR_POLARCROWNHAT_FREEZINESS_RANGE = 4
	TUNING.ARMOR_POLARCROWNHAT_FREEZINESS_RATE = 0.2
	
	TUNING.FROSTWALKERAMULET_FUEL = total_day_time * 1.5
	TUNING.FROSTWALKERAMULET_ICE_STAY_TIME = 4
	TUNING.FROSTWALKERAMULET_SLIPPINESS = TUNING.WILSON_RUN_SPEED * 10
	
	TUNING.POLARAMULET = {
		GNARWAIL_HORN = {
			ANCHOR_RAISE_MULT = 1.2,
			ROW_FORCE_MULT = 0.5,
			ROW_MAX_VELOCITY = 0.5,
			SAIL_STRENGTH_SPEED = 5,
		},
		HOUNDSTOOTH = {
			DAMAGE_MULT = 0.1,
			MOVEMENT_SPEED = 0.05,
		},
		POLARWARGSTOOTH = {
			SNOWMOVEMENT_SPEED = 0.15,
			PERISHTIME = total_day_time * 2,
		},
		WALRUS_TUSK = {
			DAPERNESS = TUNING.DAPPERNESS_TINY,
			INSULATION = TUNING.INSULATION_MED_LARGE,
			LOYALTY_MULT = 2,
		},
	}
	TUNING.POLARAMULET_PERISHATIME = total_day_time * 5
	
	TUNING.POLARMOOSEHAT_PERISHTIME = total_day_time * 5
	
	TUNING.POLARICEPACK_PRESERVE_MULT = 0.75
	
	TUNING.HEATROCK_INSULATION_POLARMULT = 0.5
	
	TUNING.GOLD_VALUES.POLARTRINKETS = {
		5, --[1] Snuggy Gnome
		5, --[2] Snuggy Gnomette
	}
	
--	Buffs
	
	TUNING.POLAR_IMMUNITY_DURATION = total_day_time
	
	TUNING.POLAR_WETNESS_LVLS = 6
	TUNING.POLAR_WETNESS_LVL_WETNESS = -0.2
	TUNING.POLAR_WETNESS_MIN_PROOFNESS = 1
	TUNING.POLAR_WETNESS_MAX_INSULATION = 120
	TUNING.POLAR_WETNESS_OVERHEATS = 36
	TUNING.POLAR_WETNESS_SNIFFNESS = 0.2
	
	TUNING.POLARWETNESS_DEBUFF_FIRE_RESIST = 0.33
	TUNING.POLARWETNESS_DEBUFF_TEMP_MODIFIER = -3.35
	TUNING.POLARWETNESS_DEBUFF_TICK = 0.5
	TUNING.POLARWETNESS_DEBUFF_STARTTEMP = TUNING.POLAR_WETNESS_OVERHEATS - (TUNING.POLAR_WETNESS_OVERHEATS / TUNING.POLAR_WETNESS_LVLS) - 1
	
--	Buildings
	
	TUNING.POLARBEARHOUSE_ENABLED = true
	TUNING.POLARBEARHOUSE_SPAWN_TIME = total_day_time * 4
	
	TUNING.POLARWALL_HEALTH = 600
	
	TUNING.POLARAMULET_STATION_SPEAKTIME = 2
	
--	Misc
	
	TUNING.ANCHOR_DEPTH_TIMES.POLAR = 5
	
	TUNING.DEEP_IN_SNOW_PLAYERDIST = 8
	TUNING.POLAR_SLOWMULT = 0.5
	TUNING.POLAR_SLOWTIME = 8
	TUNING.POLAR_COVERTIME = {min = 3, max = 10}
	TUNING.POLAR_SNOW_MELT_TEMP = 60
	TUNING.POLAR_SNOW_UPDATE_RATE = 1
	
	TUNING.SNOW_PLOW_RANGES = {
		SHOVEL = 5,
		GOLDENSHOVEL = 6,
		SHOVEL_LUNARPLANT = 7,
	}
	
	TUNING.POLAR_SNOW_FORGIVENESS = {
		PLOWING = -1,
		SNOWWAVE = -1,
	}
	
	TUNING.POLARPLOW_BLOCKER_DURATION = total_day_time * 0.8
	TUNING.POLARPLOW_BLOCKER_STORMCUT = 0.25
	TUNING.POLARPLOW_USE = 1
	
	TUNING.SHADE_POLAR_RANGE = 22
	TUNING.SHADE_POLAR_SCALE = 3.8
	
	TUNING.POLAR_STORM_COOLDOWN_MIN = total_day_time * 5
	TUNING.POLAR_STORM_COOLDOWN_MAX = total_day_time * 15
	TUNING.POLAR_STORM_LENGTH_MIN = total_day_time * 0.5
	TUNING.POLAR_STORM_LENGTH_MAX = total_day_time * 1.5
	TUNING.POLAR_STORM_TEMP_MODIFIER = -10
	
	TUNING.POLAR_STORM_FUELEDMULT = {
		CAMPFIRE = 4,
		FIREPIT = 2,
		TORCH = 3,
	}
	
	TUNING.POLAR_STORM_PROTECTION = {
		CROWN = 5,
		FIRE = 4,
		TORCH = 3,
	}
	
	TUNING.TRAP_POLARTEETH_DAMAGE = TUNING.TRAP_TEETH_DAMAGE
	TUNING.TRAP_POLARTEETH_FREEZING = 6
	TUNING.TRAP_POLARTEETH_USES = TUNING.TRAP_TEETH_USES * 5
	
	TUNING.POLAR_MIST_TIME = 15
	TUNING.POLAR_MIST_TWEENTIME = 1.5
	
	TUNING.POLAR_CC_ENABLED = GetModConfigData("misc_shader") ~= false
	TUNING.POLAR_WAVES_ENABLED = GetModConfigData("misc_snow") ~= false
	
--	Tech
	
	TUNING.PROTOTYPER_TREES.POLARAMULET_STATION = TechTree.Create({
		POLARAMULET_STATION = 2,
	})