PrefabFiles = {
	"antler_tree",
	"frostwalkeramulet",
	"icelettuce_spawner",
	"polar_dryice",
	"polar_icicles",
	"polar_mist",
	"polar_penguin",
	"polar_pillars",
	"polarbear",
	"polarbearfur",
	"polarbearhouse",
	"polarbuffs",
	"polarfox",
	"polarglobe",
	"polarice_terraformer",
	"polarmoosehat",
	"rock_polar",
	"shadowcreature_polar",
	"snowstorm_snow",
	"snowwave",
	"veggies_polar",
	"walls_polar",
	"warg_polar",
	"frosty",
	
	"polarskinprefabs",
}