local seg_time = TUNING.SEG_TIME
local day_segs = TUNING.DAY_SEGS_DEFAULT
local dusk_segs = TUNING.DUSK_SEGS_DEFAULT
local night_segs = TUNING.NIGHT_SEGS_DEFAULT
local total_day_time = TUNING.TOTAL_DAY_TIME
local day_time = seg_time * day_segs
local dusk_time = seg_time * dusk_segs
local night_time = seg_time * night_segs

--	Players
	TUNING.MIGHTINESS_POLAR_SLOWMULT = 1.5
	TUNING.MIGHTINESS_POLAR_SLOWTIME = 4
	TUNING.WIMPY_POLAR_SLOWMULT = 0.75
	TUNING.WIMPY_POLAR_SLOWTIME = -1
	TUNING.LEGDAY_POLAR_SLOWMULT = 1.25
	TUNING.LEGDAY_POLAR_SLOWTIME = 2
	
	TUNING.WEREMODE_POLAR_SLOWMULT = 1.75
	TUNING.WEREMODE_POLAR_SLOWTIME = 3
	
--	Worldgen
	TUNING.POLAR_ICICLE_DAMAGE = 300
	TUNING.POLAR_ICICLE_MINE = 3
	TUNING.POLAR_ICICLE_BREAK_CHANCE = 0.33
	TUNING.POLAR_ICICLE_GROWTIME = seg_time * 2
	TUNING.POLAR_ICICLE_GROWTIME_VARIANCE = seg_time * 2
	TUNING.POLAR_ICICLE_SPAWNTIME = seg_time * 3
	TUNING.POLAR_MAX_ICICLES = 6
	
	TUNING.POLAR_ROCK_MINE_TALL = 7
	
--	Mobs
	TUNING.POLAR_PENGUIN_HERD_SPAWN_TIMES = {min = seg_time, max = day_time}
	TUNING.POLAR_PENGUIN_MAX_IN_RANGE = 20
	TUNING.POLAR_PENGUIN_SHORE_DIST = 11
	TUNING.POLAR_PENGUIN_MATING_SEASON_BABYDELAY = 8
	TUNING.POLAR_PENGUIN_MATING_SEASON_BABYDELAY_VARIANCE = 22
	
	TUNING.POLARBEAR_HEALTH = 500
	TUNING.POLARBEAR_HEALTH_REGEN_AMOUNT = 10
	TUNING.POLARBEAR_HEALTH_REGEN_PERIOD = (500 * 2) / (total_day_time * 3) * 10
	TUNING.POLARBEAR_DAMAGE = 40
	TUNING.POLARBEAR_ATTACK_PERIOD = 1.5
	TUNING.POLARBEAR_RUN_SPEED = 6
	TUNING.POLARBEAR_WALK_SPEED = 3
	TUNING.POLARBEAR_HAT_CHANCE = 0.33
	TUNING.POLARBEAR_PLOWTIME = seg_time * 2
	
	TUNING.SHADOW_ICICLER_HEALTH = 200
	TUNING.SHADOW_ICICLER_DAMAGE = 35
	TUNING.SHADOW_ICICLER_ATTACK_PERIOD = 6
	TUNING.SHADOW_ICICLER_ATTACK_RANGE = 20
	TUNING.SHADOW_ICICLER_SPIKE_AMT = {min = 4, max = 9}
	TUNING.SHADOW_ICICLER_SPIKE_HEIGHT = {min = 8, max = 16}
	TUNING.SHADOW_ICICLER_SPIKE_RING_RANGE = {min = 4, max = 8}
	TUNING.SHADOW_ICICLER_SPIKE_RANGE = 2
	TUNING.SHADOW_ICICLER_SPEED = 4
	TUNING.SHADOW_ICICLER_SPAWN_CHANCE = 0.66
	
--	Items
	TUNING.DRYICE_FREEZABLE_COLDNESS = 0.67
	
	TUNING.POLARMOOSEHAT_PERISHTIME = total_day_time * 5
	
--	Buffs
	TUNING.POLAR_WETNESS_LVLS = 6
	TUNING.POLAR_WETNESS_LVL_WETNESS = -0.2
	TUNING.POLAR_WETNESS_MIN_PROOFNESS = 1
	TUNING.POLAR_WETNESS_MAX_INSULATION = 120
	TUNING.POLAR_WETNESS_OVERHEATS = 36
	TUNING.POLARWETNESS_DEBUFF_FIRE_RESIST = 0.33
	TUNING.POLARWETNESS_DEBUFF_TEMP_MODIFIER = -3.35
	TUNING.POLARWETNESS_DEBUFF_TICK = 0.5
	TUNING.POLARWETNESS_SNIFFNESS = 0.2
	
--	Buildings
	TUNING.POLARBEARHOUSE_ENABLED = true
	TUNING.POLARBEARHOUSE_SPAWN_TIME = total_day_time * 4
	
	TUNING.POLARWALL_HEALTH = 600
	
--	Misc
	TUNING.ANCHOR_DEPTH_TIMES.POLAR = 5
	
	TUNING.POLAR_SLOWMULT = 0.5
	TUNING.POLAR_SLOWTIME = 8
	TUNING.POLAR_TEMPERATURES = {day = -20, dusk = -40, night = -80, ice = -30}
	TUNING.POLAR_COVERTIME = {min = 3, max = 10}
	
	TUNING.POLARPLOW_BLOCKER_DURATION = total_day_time * 0.8
	TUNING.POLARPLOW_USE = 4
	
	TUNING.SHADE_POLAR_RANGE = 22
	TUNING.SHADE_POLAR_SCALE = 3.8
	
	TUNING.POLAR_MIST_TIME = 15
	TUNING.POLAR_MIST_TWEENTIME = 1.5
	
	TUNING.POLAR_CC_ENABLED = GetModConfigData("misc_shader") ~= false