PrefabFiles = {
	"polar_dryice",
	"polar_icicles",
	"polar_mist",
	"polar_penguin",
	"polar_pillars",
	"polar_walls",
	"polarbear",
	"polarbearfur",
	"polarbearhouse",
	"polarbuffs",
	"polarfox",
	"polarglobe",
	"polarice_terraformer",
	"polarmoosehat",
	"rock_polar",
	"shadowcreature_polar",
	"snowstorm_snow",
	"snowwave",
	"frostwalkeramulet",
	
	"polarskinprefabs",
}