local filters = terrain.filter

local function OnlyAllow(approved)
	local filter = {}
	
	for k, v in pairs(GetWorldTileMap()) do
		if not table.contains(approved, v) then
			table.insert(filter, v)
		end
	end
	
	return filter
end

local polar_filters = {
	antler_tree = OnlyAllow({WORLD_TILES.POLAR_SNOW}),
	antler_tree_burnt = OnlyAllow({WORLD_TILES.POLAR_SNOW}),
	antler_tree_stump = OnlyAllow({WORLD_TILES.POLAR_SNOW}),
	deciduoustree_polar = {WORLD_TILES.POLAR_ICE, WORLD_TILES.POLAR_CAVES, WORLD_TILES.PEBBLEBEACH, WORLD_TILES.POLAR_DRYICE},
	deciduoustree_polar_normal = {WORLD_TILES.POLAR_ICE, WORLD_TILES.POLAR_CAVES, WORLD_TILES.PEBBLEBEACH, WORLD_TILES.POLAR_DRYICE},
	deciduoustree_polar_short = {WORLD_TILES.POLAR_ICE, WORLD_TILES.POLAR_CAVES, WORLD_TILES.PEBBLEBEACH, WORLD_TILES.POLAR_DRYICE},
	deciduoustree_polar_tall = {WORLD_TILES.POLAR_ICE, WORLD_TILES.POLAR_CAVES, WORLD_TILES.PEBBLEBEACH, WORLD_TILES.POLAR_DRYICE},
	grass_polar = OnlyAllow({WORLD_TILES.POLAR_SNOW}),
	icelettuce_spawner = OnlyAllow({WORLD_TILES.POLAR_SNOW}),
	pillar_polar = OnlyAllow({WORLD_TILES.POLAR_CAVES, WORLD_TILES.POLAR_SNOW}),
	polarfox = OnlyAllow({WORLD_TILES.POLAR_SNOW}),
	polar_icicle_rock = OnlyAllow({WORLD_TILES.POLAR_CAVES}),
	polarbearhouse = {WORLD_TILES.POLAR_ICE},
	rock_ice_spawner_polar = OnlyAllow({WORLD_TILES.OCEAN_COASTAL, WORLD_TILES.OCEAN_POLAR, WORLD_TILES.POLAR_ICE}),
	rock_polar = OnlyAllow({WORLD_TILES.POLAR_CAVES}),
	snowwave_itemrespawner = {WORLD_TILES.POLAR_ICE, WORLD_TILES.POLAR_CAVES, WORLD_TILES.PEBBLEBEACH, WORLD_TILES.ROCKY},
	polarfish_shoalspawner_spawner_ice = OnlyAllow({WORLD_TILES.OCEAN_COASTAL, WORLD_TILES.OCEAN_POLAR, WORLD_TILES.POLAR_ICE}),
}

local polar_addedtiles = {
	catcoonden = {WORLD_TILES.POLAR_ICE, WORLD_TILES.POLAR_CAVES, WORLD_TILES.PEBBLEBEACH, WORLD_TILES.POLAR_DRYICE},
	carrot_planted = {WORLD_TILES.POLAR_ICE, WORLD_TILES.POLAR_CAVES, WORLD_TILES.PEBBLEBEACH, WORLD_TILES.POLAR_DRYICE},
	deciduoustree = {WORLD_TILES.POLAR_ICE, WORLD_TILES.POLAR_CAVES, WORLD_TILES.PEBBLEBEACH, WORLD_TILES.POLAR_DRYICE},
	deciduoustree_normal = {WORLD_TILES.POLAR_ICE, WORLD_TILES.POLAR_CAVES, WORLD_TILES.PEBBLEBEACH, WORLD_TILES.POLAR_DRYICE},
	deciduoustree_short = {WORLD_TILES.POLAR_ICE, WORLD_TILES.POLAR_CAVES, WORLD_TILES.PEBBLEBEACH, WORLD_TILES.POLAR_DRYICE},
	deciduoustree_tall = {WORLD_TILES.POLAR_ICE, WORLD_TILES.POLAR_CAVES, WORLD_TILES.PEBBLEBEACH, WORLD_TILES.POLAR_DRYICE},
	deciduoustree_burnt = {WORLD_TILES.POLAR_ICE, WORLD_TILES.POLAR_CAVES, WORLD_TILES.PEBBLEBEACH, WORLD_TILES.POLAR_DRYICE},
	deciduoustree_stump = {WORLD_TILES.POLAR_ICE, WORLD_TILES.POLAR_CAVES, WORLD_TILES.PEBBLEBEACH, WORLD_TILES.POLAR_DRYICE},
	evergreen = {WORLD_TILES.POLAR_ICE, WORLD_TILES.POLAR_CAVES, WORLD_TILES.PEBBLEBEACH, WORLD_TILES.POLAR_DRYICE},
	evergreen_normal = {WORLD_TILES.POLAR_ICE, WORLD_TILES.POLAR_CAVES, WORLD_TILES.PEBBLEBEACH, WORLD_TILES.POLAR_DRYICE},
	evergreen_short = {WORLD_TILES.POLAR_ICE, WORLD_TILES.POLAR_CAVES, WORLD_TILES.PEBBLEBEACH, WORLD_TILES.POLAR_DRYICE},
	evergreen_tall = {WORLD_TILES.POLAR_ICE, WORLD_TILES.POLAR_CAVES, WORLD_TILES.PEBBLEBEACH, WORLD_TILES.POLAR_DRYICE},
	evergreen_sparse = {WORLD_TILES.POLAR_ICE, WORLD_TILES.POLAR_CAVES, WORLD_TILES.PEBBLEBEACH, WORLD_TILES.POLAR_DRYICE},
	evergreen_sparse_normal = {WORLD_TILES.POLAR_ICE, WORLD_TILES.POLAR_CAVES, WORLD_TILES.PEBBLEBEACH, WORLD_TILES.POLAR_DRYICE},
	evergreen_sparse_short = {WORLD_TILES.POLAR_ICE, WORLD_TILES.POLAR_CAVES, WORLD_TILES.PEBBLEBEACH, WORLD_TILES.POLAR_DRYICE},
	evergreen_sparse_tall = {WORLD_TILES.POLAR_ICE, WORLD_TILES.POLAR_CAVES, WORLD_TILES.PEBBLEBEACH, WORLD_TILES.POLAR_DRYICE},
	evergreen_burnt = {WORLD_TILES.POLAR_ICE, WORLD_TILES.POLAR_CAVES, WORLD_TILES.PEBBLEBEACH, WORLD_TILES.POLAR_DRYICE},
	evergreen_stump = {WORLD_TILES.POLAR_ICE, WORLD_TILES.POLAR_CAVES, WORLD_TILES.PEBBLEBEACH, WORLD_TILES.POLAR_DRYICE},
	grass = {WORLD_TILES.POLAR_ICE, WORLD_TILES.POLAR_DRYICE},
	sapling = {WORLD_TILES.POLAR_ICE, WORLD_TILES.POLAR_DRYICE},
	leif_sparse = {WORLD_TILES.POLAR_ICE, WORLD_TILES.POLAR_DRYICE},
	marsh_tree = {WORLD_TILES.POLAR_ICE, WORLD_TILES.POLAR_CAVES, WORLD_TILES.POLAR_DRYICE},
	marsh_bush = {WORLD_TILES.POLAR_ICE, WORLD_TILES.POLAR_CAVES, WORLD_TILES.PEBBLEBEACH, WORLD_TILES.POLAR_DRYICE},
	mushtree_medium = {WORLD_TILES.POLAR_ICE, WORLD_TILES.PEBBLEBEACH, WORLD_TILES.POLAR_DRYICE},
	mushtree_small = {WORLD_TILES.POLAR_ICE, WORLD_TILES.PEBBLEBEACH, WORLD_TILES.POLAR_DRYICE},
	mushtree_tall = {WORLD_TILES.POLAR_ICE, WORLD_TILES.PEBBLEBEACH, WORLD_TILES.POLAR_DRYICE},
	mushtree_medium_stump = {WORLD_TILES.POLAR_ICE, WORLD_TILES.POLAR_DRYICE},
	mushtree_small_stump = {WORLD_TILES.POLAR_ICE, WORLD_TILES.POLAR_DRYICE},
	mushtree_tall_stump = {WORLD_TILES.POLAR_ICE, WORLD_TILES.POLAR_DRYICE},
	red_mushroom = {WORLD_TILES.POLAR_ICE, WORLD_TILES.PEBBLEBEACH, WORLD_TILES.POLAR_DRYICE},
	green_mushroom = {WORLD_TILES.POLAR_ICE, WORLD_TILES.PEBBLEBEACH, WORLD_TILES.POLAR_DRYICE},
	blue_mushroom = {WORLD_TILES.POLAR_ICE, WORLD_TILES.PEBBLEBEACH, WORLD_TILES.POLAR_DRYICE},
	twiggytree = {WORLD_TILES.POLAR_ICE, WORLD_TILES.POLAR_CAVES, WORLD_TILES.PEBBLEBEACH, WORLD_TILES.POLAR_DRYICE},
	flint = {WORLD_TILES.POLAR_ICE, WORLD_TILES.POLAR_SNOW, WORLD_TILES.POLAR_DRYICE},
	pond = {WORLD_TILES.POLAR_ICE, WORLD_TILES.POLAR_CAVES, WORLD_TILES.POLAR_DRYICE},
	pond_mos = {WORLD_TILES.POLAR_ICE, WORLD_TILES.POLAR_CAVES, WORLD_TILES.POLAR_DRYICE},
	rocks = {WORLD_TILES.POLAR_ICE, WORLD_TILES.POLAR_SNOW, WORLD_TILES.POLAR_DRYICE},
	rock1 = {WORLD_TILES.POLAR_ICE, WORLD_TILES.POLAR_SNOW, WORLD_TILES.POLAR_DRYICE},
	rock2 = {WORLD_TILES.POLAR_ICE, WORLD_TILES.POLAR_SNOW, WORLD_TILES.POLAR_DRYICE},
	rock_flintless = {WORLD_TILES.POLAR_ICE, WORLD_TILES.POLAR_DRYICE},
	rock_ice = {WORLD_TILES.POLAR_ICE, WORLD_TILES.POLAR_DRYICE},
	skeleton_notplayer_1 = {WORLD_TILES.POLAR_ICE, WORLD_TILES.PEBBLEBEACH, WORLD_TILES.POLAR_DRYICE},
	skeleton_notplayer_2 = {WORLD_TILES.POLAR_ICE, WORLD_TILES.PEBBLEBEACH, WORLD_TILES.POLAR_DRYICE},
	
	seastack = {WORLD_TILES.POLAR_SNOW},
	wobster_den = {WORLD_TILES.POLAR_SNOW},
}

for terrain, tiles in pairs(polar_filters) do
	filters[terrain] = tiles
end

for terrain, tiles in pairs(polar_addedtiles) do
	if filters[terrain] == nil then
		filters[terrain] = {}
	end
	
	for _, tile in ipairs(tiles) do
		table.insert(filters[terrain], tile)
	end
end