local ANNOUNCE = STRINGS.CHARACTERS.WX78
local DESCRIBE = STRINGS.CHARACTERS.WX78.DESCRIBE

--	Announcements
	
	--	Actions
	
	--	World, Events
	ANNOUNCE.ANNOUNCE_POLAR_SLOW = {
		"MY CHASSIS... WONT LET YOU INSIDE... SNOW.",
		"UGH...",
		"WHY WOULD... ANYONE PLAY... IN THIS SLUSH.",
	}
	ANNOUNCE.ANNOUNCE_POLARGLOBE = "COORDINATES... UNKNOWN."
	
	--	Buffs
	ANNOUNCE.ANNOUNCE_ATTACH_BUFF_POLARWETNESS = "SNOW DETECTED."
	ANNOUNCE.ANNOUNCE_DETACH_BUFF_POLARWETNESS = "YOU'RE NOT GETTING IN MY COGS THIS DAY!"
	
--	Worldgen
	
	--	Plants
	DESCRIBE.ANTLER_TREE = {
		BURNING = "IT BURNS JUST AS MUCH AS THE OTHERS.",
		BURNT = "IT BURNED DOWN.",
		CHOPPED = "MATERIAL EXTRACTED.",
		GENERIC = "YOUR HORNS WONT SAVE YOU FROM MY AXE.",
	}
	
	--	Rocks and stones
	DESCRIBE.POLAR_ICICLE = "MOTION DETECTED!"
	DESCRIBE.POLAR_ICICLE_ROCK = "THREAT LEVEL TO THE HEAD MODULE - HIGH."
	DESCRIBE.ROCK_POLAR = "AN INIFITE SOURCE OF COOL."
	
	--	Misc
	ANNOUNCE.DESCRIBE_IN_POLARSNOW = "SUBMERGED OBJECT DETECTED."
	
--	Mobs
	DESCRIBE.POLARBEAR = {
		DEAD = "YOUR DEMISE WAS EXPECTED, FLESHLING.",
		ENRAGED = "FLESHLING IS OVERCLOCKING!",
		FOLLOWER = "BOW TO ME.",
		GENERIC = "SHOWS MODERATE SIGNS OF INTELLIGENCE.",
	}
	DESCRIBE.POLARFOX = {
		FOLLOWER = "STOP FOLLOWING ME.",
		GENERIC = "YOUR CUTENESS WILL NOT SAVE YOU.",
	}
	DESCRIBE.POLARWARG = "DISPLAYS HIGH ADAPTIVITY TO ITS SURROUNDINGS."
	
--	Buildings
	
	DESCRIBE.POLARBEARHOUSE = {
		BURNT = "IT LOOKS BETTER THIS WAY.",
		GENERIC = "ITS SIZE RELATIVE TO ITS INHABITANTS DEFIES LOGIC.",
	}
	
--	Items
	
	--	Food
	DESCRIBE.ICELETTUCE = "I WILL TRAMPLE YOU."
	DESCRIBE.ICEBURRITO = "LACKS THE MOST IMPORTANT INGREDIANT. BEANZ."
	
	--	Crafting
	DESCRIBE.POLAR_DRYICE = "IT IS NOT WATER."
	DESCRIBE.POLARBEARFUR = "STUPID FLESHLING LOST ITS INSULATION"
	
	--	Equipments
	DESCRIBE.POLAR_SPEAR = "IT IS COLD AND DEADLY. PERFECT."
	DESCRIBE.POLARMOOSEHAT = "DISGUSTING HEAD INSULATION MODULE."
	
	--	Others
	DESCRIBE.POLARGLOBE = {
		GENERIC = "THESE FLESHLINGS ARE SO EASILY AMUSED.",
		INUSE = "",
		REFUEL = "NEEDS RECHARGING.",
	}
	DESCRIBE.TURF_POLAR_CAVES = "COLD GROUND."
	DESCRIBE.TURF_POLAR_DRYICE = "COLD GROUND."
	DESCRIBE.WALL_POLAR = "ADEQUATE PROTECTION."
	DESCRIBE.WALL_POLAR_ITEM = "COLD DEFENSES."