local ANNOUNCE = STRINGS.CHARACTERS.WX78
local DESCRIBE = STRINGS.CHARACTERS.WX78.DESCRIBE

--	Announcements
	
	--	Actions
	ANNOUNCE.BATTLECRY.POLARBEAR = "DIE, GREASY FLESHSACK"
	
	--	World, Events
	ANNOUNCE.ANNOUNCE_POLAR_SLOW = {
		"ENGAGING... INEFFICIENT PATHING",
		"MY CHASSIS... DO NOT BELONG... IN SNOW",
		"WHY WOULD... ANYONE PLAY... IN THIS SLUSH",
	}
	ANNOUNCE.ANNOUNCE_POLARGLOBE = "ERROR. REBOOTING WEATHER FORECAST"
	
	--	Buffs
	ANNOUNCE.ANNOUNCE_ATTACH_BUFF_POLARWETNESS = "ALERT: HIGH LEVEL OF MOISTURE IN SNOW"
	ANNOUNCE.ANNOUNCE_DETACH_BUFF_POLARWETNESS = "YOU'RE NOT GETTING IN MY COGS THIS DAY!"
	
--	Worldgen
	
	--	Plants
	DESCRIBE.ANTLER_TREE = {
		BURNING = "IT BURNS JUST AS MUCH AS THE OTHERS",
		BURNT = "IT BURNED DOWN",
		CHOPPED = "MATERIAL EXTRACTED",
		GENERIC = "YOUR HORNS WILL NOT SAVE YOU FROM MY AXE",
	}
	DESCRIBE.ICELETTUCE_SEEDS = "IT'S SOURCE CODE FOR FOOD THAT COMES FROM THE DIRT"
	
	--	Rocks and stones
	DESCRIBE.POLAR_ICICLE = "MOTION DETECTED"
	DESCRIBE.POLAR_ICICLE_ROCK = "THREAT LEVEL TO THE HEAD MODULE - HIGH."
	DESCRIBE.ROCK_POLAR = "SPINNING IS FUTILE, FLAKESACK"
	
	--	Misc
	ANNOUNCE.DESCRIBE_IN_POLARSNOW = "SUBMERGED OBJECT DETECTED"
	DESCRIBE.TUMBLEWEED_POLAR = "SPINNING IS FUTILE, FLAKESACK"
	
--	Mobs
	DESCRIBE.POLARBEAR = {
		DEAD = "YOUR DEMISE WAS EXPECTED, FLESHLING",
		ENRAGED = "FLESHLING IS OVERCLOCKING!",
		FOLLOWER = "BOW TO ME",
		GENERIC = "SHOWS MODERATE SIGNS OF INTELLIGENCE",
	}
	DESCRIBE.POLARFOX = {
		FOLLOWER = "STOP FOLLOWING ME",
		FRIEND = "YOU AGAIN",
		GENERIC = "YOUR CUTENESS WILL NOT SAVE YOU",
	}
	DESCRIBE.POLARWARG = "DISPLAYS HIGH ADAPTIVITY TO ITS SURROUNDINGS"
	
--	Buildings
	
	DESCRIBE.POLARBEARHOUSE = {
		BURNT = "IT LOOKS BETTER THIS WAY",
		GENERIC = "ITS SIZE RELATIVE TO ITS INHABITANT DEFIES LOGIC",
	}
	
--	Items
	
	--	Food
	DESCRIBE.ICELETTUCE = "I WILL TRAMPLE YOU"
	DESCRIBE.ICEBURRITO = "LACKS THE MOST IMPORTANT INGREDIANT. BEANZ."
	
	--	Crafting
	DESCRIBE.BLUEGEM_OVERCHARGED = "SO... MUCH... 01010000 01001111 01010111 01000101 01010010"
	DESCRIBE.BLUEGEM_SHARDS = "MINOR ENERGY SIGNATURE. COMBINATION REQUIRED"
	DESCRIBE.POLAR_DRYICE = "ICE, DEPLETED OF ALL ITS DISGUSTING WATER"
	DESCRIBE.POLARBEARFUR = "STUPID FLESHLING LOST ITS INSULATION"
	DESCRIBE.POLARWARGSTOOTH = "COLD AND DEADLY, LIKE ME"
	
	--	Equipments
	DESCRIBE.ANTLER_TREE_STICK = "YOUR LIMBS WILL SERVE ME, TREE"
	DESCRIBE.FROSTWALKERAMULET = "HA HA. TAKE THAT STUPID WATER"
	DESCRIBE.POLAR_SPEAR = "IT IS COLD AND DEADLY. PERFECT"
	DESCRIBE.POLARMOOSEHAT = "REVOLTING HEAD INSULATION MODULE"
	
	--	Others
	DESCRIBE.POLARGLOBE = {
		GENERIC = "FLESHLINGS ARE SO EASILY AMUSED",
		INUSE = "...HOW?",
		REFUEL = "NEEDS RECHARGING",
	}
	DESCRIBE.POLARICEPACK = "COOLING UPGRADE FOR STORAGE UNITS"
	DESCRIBE.TURF_POLAR_CAVES = "COLD GROUND"
	DESCRIBE.TURF_POLAR_DRYICE = "COLD GROUND"
	DESCRIBE.WALL_POLAR = "ADEQUATE PROTECTION"
	DESCRIBE.WALL_POLAR_ITEM = "COLD DEFENSES"