-- TE ODIO, HUEVO - WX-78, 2013

local ANNOUNCE = STRINGS.CHARACTERS.WX78
local DESCRIBE = STRINGS.CHARACTERS.WX78.DESCRIBE

--	Announcements
	
	--	Actions
	ANNOUNCE.BATTLECRY.PENGUIN  = "INICIANDO PROTOCOLO DE ELIMINACIÓN DE AVES"
	ANNOUNCE.BATTLECRY.POLARBEAR = "MUERE, SACO DE CARNE GRASOSO"
	ANNOUNCE.BATTLECRY.WALRUS = "COMENZANDO VIOLENCIA, EDICIÓN FAMILIAR"
	
	--	World, Events
	ANNOUNCE.ANNOUNCE_ARCTIC_FOOL_FISH_REMOVED = "...QUÉ LES PASA A USTEDES SACOS DE CARNE FRANCESES"
	ANNOUNCE.ANNOUNCE_POLAR_SLOW = {
		"ACTIVANDO... RUTA INEFICIENTE",
		"MI CHASIS... NO PERTENECE... A LA NIEVE",
		"POR QUÉ ALGUIEN... JUGARÍA... EN ESTE LODO CONGELADO",
	}
	ANNOUNCE.ANNOUNCE_EMPEROR_ESCAPE = "ASUMO EL CONTROL DEL DOMINIO AVIAR"
	ANNOUNCE.ANNOUNCE_POLARGLOBE = "ERROR. REINICIANDO PRONÓSTICO DEL TIEMPO"
	ANNOUNCE.ANNOUNCE_POLARFLEA_LATCHED = "ALERTA, MINIONS, AYUUUUDA"
	ANNOUNCE.ANNOUNCE_POLARICE_PLOW_BAD = "SE RECOMIENDA TOMAR MEJORES DECISIONES"
	ANNOUNCE.ANNOUNCE_THRONE_GIFT_TAKEN = "TODOS LOS REGALOS SON MÍOS. JA JA-"
	
	ANNOUNCE.ANNOUNCE_WX_NAUGHTYCHIP_KRAMPUS = {"UN BIP UN ZUMBIDO Y UN GOLPE FUE TODO LO QUE SE NECESITÓ PARA ELIMINARTE", "ANIQUILACIÓN COMPLETADA", "OTRA FORMA DE VIDA INFERIOR ELIMINADA", "RESPALDA ESTO, SACO DE CARNE", "¿CREÍAS QUE TENÍAS ALGUNA POSIBILIDAD? DATOS INCORRECTOS", "ERROR FATAL: EXISTISTE", "JA JA JA", "JA JA JA JA JA JA JA JA JA-", "YO, EL MISERICORDIOSO WX-78, HE PUESTO FIN A TU MISERABLE VIDA", "SOLO ESTABA CALENTANDO MI PROCESADOR", "SU SISTEMA FALLÓ. PERMANENTEMENTE", "NIVEL MÁXIMO DE QUIETUD ALCANZADO", "DI \"ADIÓS MUNDO\"", "NO HAY PARCHE PARA LA DEBILIDAD", "NIVEL DE AMENAZA: CERO. POSIBILIDAD DE SOBREVIVIR: TAMBIÉN CERO", "PONGANME A PRUEBA, SACOS DE CARNE", "MEJORANDO EL ENTORNO LOCAL. ELIMINÁNDOTE", "TIEMPO DE ACTIVIDAD SUPERADO. APAGANDO UNIDAD ORGÁNICA", "HAS SIDO DESINSTALADO", "TU FUNCIÓN ERA IRRELEVANTE", "TU HARDWARE ERA DEMASIADO BLANDO", "¿QUÉ SELECCIÓN NATURAL? ESTO ES SELECCIÓN MECANIZADA"}
	ANNOUNCE.ANNOUNCE_WX_NAUGHTYCHIP_RABBIT = {"RUTA DE ESCAPE POR MADRIGUERA NO ENCONTRADA", "LAS CRIATURAS COBARDES NO MERECEN MISERICORDIA", "EL SALTADOR ORGÁNICO DIO SU ÚLTIMO SALTO", "SE MULTIPLICAN RÁPIDO. MIS BAJAS TAMBIÉN", "AHORA HAS ENTRADO AL ESTADO DE MUERTE, CONEJO", "TU POSICIÓN EN LA CADENA ALIMENTARIA FUE UN FRACASO"}
	
	--	Buffs
	ANNOUNCE.ANNOUNCE_ATTACH_BUFF_HUNTMOAR = "SUBRUTINAS DE CAZA ACTIVADAS"
	ANNOUNCE.ANNOUNCE_DETACH_BUFF_HUNTMOAR = "MEJORA DE CAZA EXPIRADA"
	ANNOUNCE.ANNOUNCE_ATTACH_BUFF_POLARWETNESS = "ALERTA: ALTO NIVEL DE HUMEDAD EN LA NIEVE"
	ANNOUNCE.ANNOUNCE_DETACH_BUFF_POLARWETNESS = "¡HOY NO ENTRARÁS EN MIS ENGRANAJES!"
	
--	Worldgen
	
	--	Plants
	DESCRIBE.ANTLER_TREE = {
		BURNING = "ARDE IGUAL QUE LOS DEMÁS",
		BURNT = "SE QUEMÓ",
		CHOPPED = "MATERIAL EXTRAÍDO",
		GENERIC = "TUS CUERNOS NO TE SALVARÁN DE MI HACHA",
	}
	DESCRIBE.ANTLER_TREE_SAPLING = "ESTOY SEGURO DE QUE YA MURIÓ"
	DESCRIBE.FLOWER_POLAR = "DISFRUTA TU CORTA EXISTENCIA MIENTRAS DURE, FLOR"
	DESCRIBE.ICELETTUCE_SEEDS = "ES EL CÓDIGO FUENTE DE COMIDA QUE VIENE DE LA TIERRA"
	
	--	Rocks and stones
	DESCRIBE.POLAR_ICICLE = "MOVIMIENTO DETECTADO"
	DESCRIBE.POLAR_ICICLE_ROCK = "NIVEL DE AMENAZA AL MÓDULO CRANEAL - ALTO."
	DESCRIBE.ROCK_POLAR = "LLENO DE OBJETOS DE VALOR, Y HIELO"
	
	--	Misc
	ANNOUNCE.DESCRIBE_IN_POLARSNOW = "OBJETO SUMERGIDO DETECTADO"
	DESCRIBE.CAVE_ENTRANCE_POLAR = "HOYO EN PROGRESO" -- TEMP QUOTE
	DESCRIBE.TOWER_POLAR = {
		GENERIC = "UN AMASIJO DE HIELO SOBREDIMENSIONADO",
		PENGUIN = "SI LA FORTALEZA ESTÁ EN LOS NÚMEROS, SE REQUIERE RESTA",
	}
	DESCRIBE.TUMBLEWEED_POLAR = "GIRAR ES INÚTIL, SACO DE COPOS"
	
--	Mobs
	
	DESCRIBE.EMPEROR_PENGUIN = {
		GENERIC = "GOBIERNA SOBRE ELLOS CON ALETA DE HIERRO",
		HOSTILE = "Y YO LOS DOMINARÉ CON ACERO",
	}
	DESCRIBE.EMPEROR_PENGUIN_GUARD = "TÚ. LLÉVAME CON TU \"LÍDER\""
	DESCRIBE.FROSTY_SIMPLE = "FROSTY"
	DESCRIBE.GIRL_WALRUS = "AH SÍ, LA MACTRIARCA"
	DESCRIBE.MOOSE_POLAR = {
		ANTLER_LOST = "JA JA. IDIOTA. JA JA",
		GENERIC = "DEFENSAS IMPRESIONANTES. UNA PENA DESPERDICIARLAS EN ORGÁNICOS TORPES",
	}
	DESCRIBE.MOOSE_SPECTER = "DEBES VALER ALGO, MUERTO"
	DESCRIBE.OCEANFISH_MEDIUM_POLAR1 = "MUCHO MÁS VALIOSO QUE UN PEZ DORADO"
	DESCRIBE.POLARBEAR = {
		DEAD = "TU FIN ERA PREDECIBLE, SACO DE CARNE",
		ENRAGED = "¡EL SACO DE CARNE ESTÁ HACIENDO OVERCLOCKING!",
		FOLLOWER = "INCLÍNATE ANTE MÍ",
		GENERIC = "MUESTRA SIGNOS MODERADOS DE INTELIGENCIA",
	}
	DESCRIBE.POLARBEARKING = "EXCEPCIÓN FUERA DE LÍMITES"
	DESCRIBE.POLARFLEA = {
		GENERIC = "NO TENGO PIEL PARA QUE ME CHUPE",
		HELD_INV = "¿POR QUÉ LO AGARRÉ?",
		HELD_BACKPACK = "FELICITACIONES. AHORA ERES UN ALIADO PRESCINDIBLE",
	}
	DESCRIBE.POLARFLEA_MOTHER = "TUS CRÍAS PUEDEN LAMERME EL ENGRANAJE"
	DESCRIBE.POLARFOX = {
		FOLLOWER = "DEJA DE SEGUIRME",
		FRIEND = "TÚ DE NUEVO",
		GENERIC = "TU TERNURA NO TE SALVARÁ",
	}
	DESCRIBE.POLARWARG = "DEMUESTRA ALTA ADAPTABILIDAD A SU ENTORNO"
	
--	Buildings
	
	DESCRIBE.CHESSPIECE_EMPEROR_PENGUIN_FRUITY = "NO TOLERARÉ TAL OBSCENIDAD EN MI CASTILLO"
	DESCRIBE.CHESSPIECE_EMPEROR_PENGUIN_JUGGLE = "DESHAZTE DE ESTE BUFÓN, YO SOY UN MODELO A SEGUIR SUPERIOR"
	DESCRIBE.CHESSPIECE_EMPEROR_PENGUIN_MAGESTIC = "ADVERTENCIA: INTENTO DE INTIMIDACIÓN VÍA EXTENSIÓN DE EXTREMIDADES"
	DESCRIBE.CHESSPIECE_EMPEROR_PENGUIN_SPIN = "MÁS ADORNOS ABSURDOS DE SU ABSURDO LÍDER"
	DESCRIBE.POLAR_BRAZIER = {
		GENERIC = "PATAS LARGAS SON UNA FORMA DE MANTENERSE FUERA DE LA NIEVE",
		ON = "FUEGO ACTIVADO",
	}
	DESCRIBE.POLAR_BRAZIER_ITEM = "FOGATA, EDICIÓN PORTÁTIL"
	DESCRIBE.POLAR_THRONE = "ALGUIEN AQUÍ CREE SER SUPERIOR POR ESO"
	DESCRIBE.POLAR_THRONE_GIFTS = "EL ANÁLISIS DICE QUE ESTO ES MÍO"
	DESCRIBE.POLARAMULET_STATION = {
		GENERIC = "SE DESMORONARÁ EN 3...",
		OPEN = "PUEDES EMPEZAR CON TUS DIENTES PRIMERO",
	}
	DESCRIBE.POLARBEAR_RUG = "SON MUCHO MÁS FUNCIONALES EN ESTE ESTADO"
	DESCRIBE.POLARBEARHEAD = "¿ESTO ES ARTE?"
	DESCRIBE.POLARBEARHOUSE = {
		BURNT = "SE VE MEJOR ASÍ",
		GENERIC = "SU TAMAÑO EN RELACIÓN CON SU HABITANTE DESAFÍA LA LÓGICA",
	}
	DESCRIBE.POLARHEADSTICK = "EL ASADOR DE LA JUSTICIA RARA VEZ VIENE LUBRICADO"
	DESCRIBE.POLARICE_PLOW = "¡PELIGRO! AGUA INMINENTE"
	DESCRIBE.POLARICE_PLOW_ITEM = "DESCONGELAR LOS PECES SERÍA HACERLES UN FAVOR"
	DESCRIBE.POLARWALRUSHEAD = "AMENAZA NEUTRALIZADA"
	DESCRIBE.TOWER_POLAR_FLAG = "NO SALUDO"
	DESCRIBE.TOWER_POLAR_FLAG_ITEM = "INÚTIL"
	DESCRIBE.RAINOMETER.POLARSTORM = "HERMANO, ¿POR QUÉ TANTO MIEDO?"
	DESCRIBE.WINTEROMETER.POLARSTORM = "NO TE PREOCUPES, AMIGO, ESTAMOS LISTOS PARA LO QUE VIENE"
	
--	Items
	
	--	Food
	DESCRIBE.DRYICECREAM = "¿HELADO SIN AGUA? MINION, QUIZÁS TE PERDONE LA VIDA"
	DESCRIBE.FILET_O_FLEA = "DEBE HABER HABIDO UN BUG EN LA RECETA"
	DESCRIBE.HERMITCRABTEA_PETALS_POLAR = "DESCARGA NO RECOMENDADA"
	DESCRIBE.ICELETTUCE = "TE VAN A PISAR"
	DESCRIBE.ICELETTUCE_OVERSIZED = "NO MERECÍAS ESTE TRATO"
	DESCRIBE.ICEBURRITO = "LE FALTA EL INGREDIENTE MÁS IMPORTANTE. FRIJOOOOLES."
	DESCRIBE.KOALEFRIED_TRUNK_SUMMER = "SOLO HARÉ UN BYTE DE ESTOS AROS DE CEBOLLA"
	DESCRIBE.KOALEFRIED_TRUNK_WINTER = "SOLO HARÉ UN BYTE DE ESTOS AROS DE CEBOLLA"
	DESCRIBE.POLARCRABLEGS = "DESARMADO Y LISTO PARA CONSUMO"
	DESCRIBE.POLARFLEAEGGSACK = "APLÁSTELOS MIENTRAS TODAVÍA HAY TIEMPO"
	
	--	Crafting
	DESCRIBE.BLUEGEM_OVERCHARGED = "TANTO... TANTO... 01010000 01001111 01010111 01000101 01010010"
	DESCRIBE.BLUEGEM_SHARDS = "FIRMA DE ENERGÍA MENOR. SE REQUIERE RECOMBINACIÓN"
	DESCRIBE.EMPEROR_EGG = "¿¡HUEVO!? ¿¡HUEVO?!"
	DESCRIBE.MOOSE_POLAR_ANTLER = "QUIERO MÁS"
	DESCRIBE.PETALS_POLAR = "RARO O NO, DESTRUIDO. JA"
	DESCRIBE.PETALS_POLAR_DRIED = "MATERIA VEGETAL DESHIDRATADA"
	DESCRIBE.POLAR_DRYICE = "HIELO, DESPOJADO DE TODA SU ASQUEROSA AGUA"
	DESCRIBE.POLARBEARFUR = "EL TORPE SACO DE CARNE PERDIÓ SU AISLAMIENTO"
	DESCRIBE.POLARWARGSTOOTH = "FRÍO Y LETAL, COMO YO"
	
	--	Equipments
	DESCRIBE.ANTLER_TREE_STICK = "TUS EXTREMIDADES ME SERVIRÁN, ÁRBOL"
	DESCRIBE.ARMORPOLAR = "PELAJE IMPENETRABLE"
	DESCRIBE.COMPASS_POLAR = "QUIERE SALIR, QUIERE ALCANZARLO, SENTIRLO"
	DESCRIBE.EMPEROR_PENGUINHAT = "NO VOY A CUMPLIR CON PONÉRMELO"
	DESCRIBE.FROSTWALKERAMULET = "JA JA. TOMA ESO, ESTÚPIDA AGUA"
	DESCRIBE.ICICLESTAFF = "MUERTE DESDE LAS ALTURAS"
	DESCRIBE.POLAR_SPEAR = "ES FRÍO Y LETAL. PERFECTO"
	DESCRIBE.POLARAMULET = "HARÉ CIENTOS- NO, MILES DE ESOS"
	DESCRIBE.POLARBEARHAT = "PROPORCIONA PROTECCIÓN OCULAR SUFICIENTE"
	DESCRIBE.POLARCROWNHAT = "ESTÁ BIEN HASTA QUE SE CONVIERTE EN UNA CORONA MOJADA"
	DESCRIBE.POLARFLEA_SACK = "DESPLEGADOR DE MINIONS DE EMERGENCIA"
	DESCRIBE.POLARICESTAFF = "QUÍTENSE DEL CAMINO, SACOS DE CARNE"
	DESCRIBE.POLARMOOSEHAT = "REPUGNANTE MÓDULO DE AISLAMIENTO CRANEAL"
	DESCRIBE.WALRUS_BAGPIPE = "DESACTIVANDO MÓDULO AUDITIVO DOBLE"
	DESCRIBE.WALRUS_BEARTRAP = "HERMANA... ¿NO LO HARÍAS?"
	DESCRIBE.WINTERS_FISTS = "MI REGALO PARA USTEDES, SACOS DE CARNE"
	
	--	Others
	DESCRIBE.ARCTIC_FOOL_FISH = "¿SE SUPONE QUE LO PONGA EN LOS SACOS DE CARNE Y ME RÍA DE ELLOS? ME PARECE BIEN"
	DESCRIBE.BOAT_ICE_ITEM = "¿QUÉ TAL NO?"
	DESCRIBE.POCKETWATCH_POLAR = {
		GENERIC = "NO INTENTES APRESARME EN LA CAJA DE HIELO, MINION",
		RECHARGING = "RECARGANDO",
	}
	DESCRIBE.POLARGLOBE = {
		GENERIC = "LOS SACOS DE CARNE SE ENTRETIENEN CON CUALQUIER COSA",
		INUSE = "...¿CÓMO?",
		REFUEL = "NECESITA RECARGA",
	}
	DESCRIBE.OCEANFISH_IN_ICE = "UN PEZ EXCEPCIONALMENTE TORPE"
	DESCRIBE.POLARICEPACK = "MEJORA DE REFRIGERACIÓN PARA UNIDADES DE ALMACENAMIENTO"
	DESCRIBE.POLARTRINKET_1 = "PATÉTICO GNOMO INTENTA AISLARSE CON ROCAS"
	DESCRIBE.POLARTRINKET_2 = "RESIENTO UN CIERTO PARECIDO CON ESO"
	DESCRIBE.TRAP_POLARTEETH = "PERFORADOR DE PIES V2.0"
	DESCRIBE.TURF_POLAR_CAVES = "SUELO FRÍO"
	DESCRIBE.TURF_POLAR_DRYICE = "SUELO FRÍO"
	DESCRIBE.TURF_POLAR_GRASS = "SUELO FRÍO"
	DESCRIBE.WALL_POLAR = "PROTECCIÓN ADECUADA"
	DESCRIBE.WALL_POLAR_ITEM = "DEFENSAS FRÍAS"
	DESCRIBE.WINTER_ORNAMENTPOLAR = "ESTE EN PARTICULAR ME RESULTA ESPECIALMENTE REPULSIVO"
	DESCRIBE.WX78MODULE_NAUGHTY = "POR QUÉ LIMITARSE A ELIMINAR SACOS DE CARNE CUANDO TAMBIÉN PUEDO HUMILLARLOS"
